language: c
os:
  - linux
  - windows
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
      - cmake
before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ./travis/install.win.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./travis/install.linux.sh; fi

script:
  - cmake --version
  - make --version
  - mkdir build && cd build && cmake .. && (cmake --build . --config Debug && ctest --output-on-failure)
  - gcc --version
